# Generated by Django 4.2.30 on 2026-08-08 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_categoria_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen representativa de la categoría VIP', null=True, upload_to='categorias_vip/')),
            ],
            options={
                'verbose_name': 'Categoría VIP',
                'verbose_name_plural': 'Categorías VIP',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen del producto VIP (máx 5MB)', null=True, upload_to='productos_vip/')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='menu_app.categoriavip')),
            ],
            options={
                'verbose_name': 'Producto VIP',
                'verbose_name_plural': 'Productos VIP',
                'ordering': ['categoria__orden', 'categoria__nombre', 'nombre'],
            },
        ),
    ]
